# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='Tripset',
        ),
    ]
