# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 23:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_auto_20171128_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('center', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('shape', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BoroughDistrict',
            fields=[
                ('district_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxi.District')),
                ('fip', models.CharField(max_length=5)),
            ],
            bases=('taxi.district',),
        ),
        migrations.CreateModel(
            name='CityDistrict',
            fields=[
                ('district_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taxi.District')),
                ('ntacode', models.CharField(max_length=5)),
                ('area', models.FloatField()),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.BoroughDistrict')),
            ],
            bases=('taxi.district',),
        ),
    ]
