# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_boroughdistrict_citydistrict_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripset',
            name='trips',
            field=models.ManyToManyField(to='taxi.Trip'),
        ),
    ]
