# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_auto_20171218_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(null=True)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_head', to='taxi.District')),
                ('tail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_as_tail', to='taxi.District')),
                ('tripset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='taxi.Tripset')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='dropoffDistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_by_dropoff', to='taxi.District'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickupDistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_by_pickup', to='taxi.District'),
        ),
    ]
