# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_auto_20171218_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripset',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='set', to='taxi.Trip'),
        ),
    ]
